// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddGame(arg1:string,arg2:string):Promise<string>;

export function GetAllGames():Promise<Array<models.Game>>;

export function GetAltsByGame(arg1:string):Promise<Array<models.AltAccount>>;
