// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAlt(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddAlt'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddGame(arg1, arg2) {
  return window['go']['main']['App']['AddGame'](arg1, arg2);
}

export function DeleteAlt(arg1) {
  return window['go']['main']['App']['DeleteAlt'](arg1);
}

export function DeleteGame(arg1) {
  return window['go']['main']['App']['DeleteGame'](arg1);
}

export function GetAllGames() {
  return window['go']['main']['App']['GetAllGames']();
}

export function GetAltsByGame(arg1) {
  return window['go']['main']['App']['GetAltsByGame'](arg1);
}

export function UpdateAlt(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateAlt'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateGame(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGame'](arg1, arg2, arg3);
}

export function UpdateGamePlaytime(arg1, arg2) {
  return window['go']['main']['App']['UpdateGamePlaytime'](arg1, arg2);
}
