// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddAlt(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:Record<string, any>):Promise<string>;

export function AddGame(arg1:string,arg2:string):Promise<string>;

export function DeleteAlt(arg1:string):Promise<void>;

export function DeleteGame(arg1:string):Promise<void>;

export function GetAllGames():Promise<Array<models.Game>>;

export function GetAltsByGame(arg1:string):Promise<Array<models.AltAccount>>;

export function UpdateAlt(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:Record<string, any>):Promise<void>;

export function UpdateGame(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateGamePlaytime(arg1:string,arg2:number):Promise<void>;
