// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGame(arg1, arg2) {
  return window['go']['main']['App']['AddGame'](arg1, arg2);
}

export function GetAllGames() {
  return window['go']['main']['App']['GetAllGames']();
}

export function GetAltsByGame(arg1) {
  return window['go']['main']['App']['GetAltsByGame'](arg1);
}
